.TH SLOCK 1 slock\-VERSION
.SH NAME
slock \- simple X display locker
.SH SYNOPSIS
.B slock
.RB [ \-v
|
.IR post_lock_command ]
.SH DESCRIPTION
.B slock
is a screen locker for X. If provided, the
.IR post_lock_command
will be executed when the screen is locked.
.SH OPTIONS
.TP
.B \-v
prints version information to stdout, then exits.
.SH EXAMPLES
$ slock /usr/sbin/s2ram
.SH CUSTOMIZATION
.B slock
can be customized by creating a custom config.h and (re)compiling the source
code. This keeps it fast, secure and simple.
.SH AUTHORS
See the LICENSE file for the authors.
.SH LICENSE
See the LICENSE file for the terms of redistribution.
.SH BUGS
Please report them.
